### ISSUE TITLE
tegracli.conf.yml, not tegracli.conf.yaml

### ISSUE THREAD

**Issue by JanEggers-hr** [Leibniz-HBI/tegracli#31]
According to the code, the script is looking for a valid config in ```tegracli.conf.yml``` - so if you use the supplied template file, the computer won't find it (at least a Mac or Linux machine won't).

**Comment by FlxVctr** [comment]
@JanEggers-hr Just to be sure, you're referring to the filename in the README? Or do I miss something

**Comment by JanEggers-hr** [comment]
Yes, you're right. I thought the template file in the repository was .yaml as well, my bad.

**Comment by JanEggers-hr** [comment]
Fixed!
