### ISSUE TITLE
feat: add rehydration command 

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/tegracli#39]
idea: take a txt-file with channel and message ids per line and rehydrate these as full messages as `twarc`would.

**Comment by FlxVctr** [comment]
why?

**Comment by pekasen** [comment]
E.g. for tracking metrics of individual messages over time, detecting deleted messages and sharing data sets.

**Comment by FlxVctr** [comment]
Well, for sharing datasets I am not sure whether it's really necessary. That's rather a nod to Twitter's TOS. But yeah, if we do not want to sent GB of data, maybe sometimes it makes  sense. But the updating of metrics makes sense nevertheless

**Comment by pekasen** [comment]
OK, ready now, as @JanRau needs it urgently.
